CREATE TABLE IF NOT EXISTS member_profiles (
    id            INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id       INT UNSIGNED NOT NULL UNIQUE,
    first_name    VARCHAR(100) NOT NULL,
    middle_name   VARCHAR(100) DEFAULT NULL,
    last_name     VARCHAR(100) NOT NULL,
    picture_url   VARCHAR(500) NOT NULL,
    level         VARCHAR(100) DEFAULT NULL,
    year          VARCHAR(100) DEFAULT NULL,
    semester      VARCHAR(100) DEFAULT NULL,
    bio           TEXT DEFAULT NULL,
    skills        TEXT DEFAULT NULL,
    languages     TEXT DEFAULT NULL,
    website       VARCHAR(500) DEFAULT NULL,
    email_contact VARCHAR(255) DEFAULT NULL,
    github        VARCHAR(500) DEFAULT NULL,
    linkedin      VARCHAR(500) DEFAULT NULL,
    twitter       VARCHAR(500) DEFAULT NULL,
    certificates  TEXT DEFAULT NULL,
    status        ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;
