<?php
namespace App\Models;
use App\Config\Database;
class Booking {
    public int $id; public int $facility_id; public int $user_id; public string $title; public string $start_time; public string $end_time; public string $status; public ?int $approved_by; public string $created_at; public string $updated_at;
    public function __construct(array $d) { $this->id=(int)$d['id'];$this->facility_id=(int)$d['facility_id'];$this->user_id=(int)$d['user_id'];$this->title=$d['title'];$this->start_time=$d['start_time'];$this->end_time=$d['end_time'];$this->status=$d['status'];$this->approved_by=isset($d['approved_by'])?(int)$d['approved_by']:null;$this->created_at=$d['created_at'];$this->updated_at=$d['updated_at']??$d['created_at']; }
    public static function findById(int $id): ?self { $db=Database::getInstance();$stmt=$db->prepare('SELECT * FROM bookings WHERE id=? LIMIT 1');$stmt->execute([$id]);$row=$stmt->fetch();return $row?new self($row):null; }
    public static function findAll(array $filters=[],int $page=1,int $perPage=20): array { $db=Database::getInstance();$where=[];$params=[];if(!empty($filters['facility_id'])){$where[]='facility_id=?';$params[]=(int)$filters['facility_id'];}if(!empty($filters['user_id'])){$where[]='user_id=?';$params[]=(int)$filters['user_id'];}if(!empty($filters['status'])){$where[]='status=?';$params[]=$filters['status'];}if(!empty($filters['date_from'])){$where[]='start_time>=?';$params[]=$filters['date_from'];}if(!empty($filters['date_to'])){$where[]='end_time<=?';$params[]=$filters['date_to'];}$wc=$where?'WHERE '.implode(' AND ',$where):'';$offset=($page-1)*$perPage;$stmt=$db->prepare("SELECT * FROM bookings {$wc} ORDER BY start_time DESC LIMIT ? OFFSET ?");$params[]=$perPage;$params[]=$offset;$stmt->execute($params);return array_map(fn($r)=>new self($r),$stmt->fetchAll()); }
    public static function create(array $d): self { $db=Database::getInstance();$stmt=$db->prepare('INSERT INTO bookings (facility_id,user_id,title,start_time,end_time,status) VALUES (?,?,?,?,?,?)');$stmt->execute([$d['facility_id'],$d['user_id'],$d['title'],$d['start_time'],$d['end_time'],$d['status']??'pending']);return self::findById((int)$db->lastInsertId()); }
    public function approve(int $userId): bool { $db=Database::getInstance();$stmt=$db->prepare('UPDATE bookings SET status=?,approved_by=? WHERE id=?');return $stmt->execute(['approved',$userId,$this->id]); }
    public function reject(int $userId): bool { $db=Database::getInstance();$stmt=$db->prepare('UPDATE bookings SET status=?,approved_by=? WHERE id=?');return $stmt->execute(['rejected',$userId,$this->id]); }
    public function toArray(): array { return ['id'=>$this->id,'facility_id'=>$this->facility_id,'user_id'=>$this->user_id,'title'=>$this->title,'start_time'=>$this->start_time,'end_time'=>$this->end_time,'status'=>$this->status,'approved_by'=>$this->approved_by,'created_at'=>$this->created_at]; }
}
