<?php
namespace App\Models;
use App\Config\Database;
class Course {
    public int $id; public string $code; public string $name; public ?string $description; public ?int $department_id; public int $credits; public ?int $teacher_id; public ?int $semester_id; public ?int $max_students; public string $status; public string $created_at; public string $updated_at;
    public function __construct(array $d) { $this->id=(int)$d["id"];$this->code=$d["code"];$this->name=$d["name"];$this->description=$d["description"]??null;$this->department_id=isset($d["department_id"])?(int)$d["department_id"]:null;$this->credits=(int)$d["credits"];$this->teacher_id=isset($d["teacher_id"])?(int)$d["teacher_id"]:null;$this->semester_id=isset($d["semester_id"])?(int)$d["semester_id"]:null;$this->max_students=isset($d["max_students"])?(int)$d["max_students"]:null;$this->status=$d["status"];$this->created_at=$d["created_at"];$this->updated_at=$d["updated_at"]??$d["created_at"]; }
    public static function findById(int $id): ?self { $db=Database::getInstance();$stmt=$db->prepare("SELECT * FROM courses WHERE id=? LIMIT 1");$stmt->execute([$id]);$row=$stmt->fetch();return $row?new self($row):null; }
    public static function findByCode(string $code): ?self { $db=Database::getInstance();$stmt=$db->prepare("SELECT * FROM courses WHERE code=? LIMIT 1");$stmt->execute([$code]);$row=$stmt->fetch();return $row?new self($row):null; }
    public static function findAll(array $filters=[],int $page=1,int $perPage=20): array { $db=Database::getInstance();$where=[];$params=[];if(!empty($filters["department_id"])){$where[]="department_id=?";$params[]=(int)$filters["department_id"];}if(!empty($filters["teacher_id"])){$where[]="teacher_id=?";$params[]=(int)$filters["teacher_id"];}if(!empty($filters["semester_id"])){$where[]="semester_id=?";$params[]=(int)$filters["semester_id"];}if(!empty($filters["status"])){$where[]="status=?";$params[]=$filters["status"];}$wc=$where?"WHERE ".implode(" AND ",$where):"";$offset=($page-1)*$perPage;$stmt=$db->prepare("SELECT * FROM courses {$wc} ORDER BY created_at DESC LIMIT ? OFFSET ?");$params[]=$perPage;$params[]=$offset;$stmt->execute($params);return array_map(fn($r)=>new self($r),$stmt->fetchAll()); }
    public static function countAll(array $filters=[]): int { $db=Database::getInstance();$where=[];$params=[];if(!empty($filters["department_id"])){$where[]="department_id=?";$params[]=(int)$filters["department_id"];}if(!empty($filters["teacher_id"])){$where[]="teacher_id=?";$params[]=(int)$filters["teacher_id"];}$wc=$where?"WHERE ".implode(" AND ",$where):"";$stmt=$db->prepare("SELECT COUNT(*) FROM courses {$wc}");$stmt->execute($params);return (int)$stmt->fetchColumn(); }
    public static function create(array $d): self { $db=Database::getInstance();$stmt=$db->prepare("INSERT INTO courses (code,name,description,department_id,credits,teacher_id,semester_id,max_students,status) VALUES (?,?,?,?,?,?,?,?,?)");$stmt->execute([$d["code"],$d["name"],$d["description"]??null,$d["department_id"]??null,$d["credits"]??3,$d["teacher_id"]??null,$d["semester_id"]??null,$d["max_students"]??null,$d["status"]??"active"]);return self::findById((int)$db->lastInsertId()); }
    public function update(array $d): bool { $db=Database::getInstance();$sets=[];$params=[];$allowed=["name","description","department_id","credits","teacher_id","semester_id","max_students","status","code"];foreach($allowed as $f){if(array_key_exists($f,$d)){$sets[]="{$f}=?";$params[]=$d[$f];}}if(empty($sets))return false;$params[]=$this->id;$stmt=$db->prepare("UPDATE courses SET ".implode(",",$sets)." WHERE id=?");return $stmt->execute($params); }
    public function delete(): bool { $db=Database::getInstance();$stmt=$db->prepare("DELETE FROM courses WHERE id=?");return $stmt->execute([$this->id]); }
    public function toArray(): array { return ["id"=>$this->id,"code"=>$this->code,"name"=>$this->name,"description"=>$this->description,"department_id"=>$this->department_id,"credits"=>$this->credits,"teacher_id"=>$this->teacher_id,"semester_id"=>$this->semester_id,"max_students"=>$this->max_students,"status"=>$this->status,"created_at"=>$this->created_at]; }
}
