<?php
namespace App\Models;
use App\Config\Database;
class Incident {
    public int $id; public string $title; public string $description; public string $severity; public string $status; public ?int $assignee_id; public int $reported_by; public ?string $resolved_at; public string $created_at; public string $updated_at;
    public function __construct(array $d) { $this->id=(int)$d['id'];$this->title=$d['title'];$this->description=$d['description'];$this->severity=$d['severity'];$this->status=$d['status'];$this->assignee_id=isset($d['assignee_id'])?(int)$d['assignee_id']:null;$this->reported_by=(int)$d['reported_by'];$this->resolved_at=$d['resolved_at']??null;$this->created_at=$d['created_at'];$this->updated_at=$d['updated_at']??$d['created_at']; }
    public static function findById(int $id): ?self { $db=Database::getInstance();$stmt=$db->prepare('SELECT * FROM incidents WHERE id=? LIMIT 1');$stmt->execute([$id]);$row=$stmt->fetch();return $row?new self($row):null; }
    public static function findAll(array $filters=[],int $page=1,int $perPage=20): array { $db=Database::getInstance();$where=[];$params=[];if(!empty($filters['severity'])){$where[]='severity=?';$params[]=$filters['severity'];}if(!empty($filters['status'])){$where[]='status=?';$params[]=$filters['status'];}if(!empty($filters['assignee_id'])){$where[]='assignee_id=?';$params[]=(int)$filters['assignee_id'];}$wc=$where?'WHERE '.implode(' AND ',$where):'';$offset=($page-1)*$perPage;$stmt=$db->prepare("SELECT * FROM incidents {$wc} ORDER BY created_at DESC LIMIT ? OFFSET ?");$params[]=$perPage;$params[]=$offset;$stmt->execute($params);return array_map(fn($r)=>new self($r),$stmt->fetchAll()); }
    public static function create(array $d): self { $db=Database::getInstance();$stmt=$db->prepare('INSERT INTO incidents (title,description,severity,status,assignee_id,reported_by) VALUES (?,?,?,?,?,?)');$stmt->execute([$d['title'],$d['description'],$d['severity']??'medium',$d['status']??'open',$d['assignee_id']??null,$d['reported_by']]);return self::findById((int)$db->lastInsertId()); }
    public function assign(int $assigneeId): bool { $db=Database::getInstance();$stmt=$db->prepare('UPDATE incidents SET assignee_id=?,status=? WHERE id=?');return $stmt->execute([$assigneeId,'investigating',$this->id]); }
    public function resolve(): bool { $db=Database::getInstance();$stmt=$db->prepare('UPDATE incidents SET status=?,resolved_at=NOW() WHERE id=?');return $stmt->execute(['resolved',$this->id]); }
    public function toArray(): array { return ['id'=>$this->id,'title'=>$this->title,'description'=>$this->description,'severity'=>$this->severity,'status'=>$this->status,'assignee_id'=>$this->assignee_id,'reported_by'=>$this->reported_by,'resolved_at'=>$this->resolved_at,'created_at'=>$this->created_at]; }
}
