<?php
namespace App\Models;
use App\Config\Database;
class SportsEvent {
    public int $id; public string $title; public ?string $description; public string $sport_type; public string $event_date; public ?string $location; public ?int $team1_id; public ?int $team2_id; public int $team1_score; public int $team2_score; public string $status; public int $created_by; public string $created_at; public string $updated_at;
    public function __construct(array $d) { $this->id=(int)$d['id'];$this->title=$d['title'];$this->description=$d['description']??null;$this->sport_type=$d['sport_type'];$this->event_date=$d['event_date'];$this->location=$d['location']??null;$this->team1_id=isset($d['team1_id'])?(int)$d['team1_id']:null;$this->team2_id=isset($d['team2_id'])?(int)$d['team2_id']:null;$this->team1_score=(int)$d['team1_score'];$this->team2_score=(int)$d['team2_score'];$this->status=$d['status'];$this->created_by=(int)$d['created_by'];$this->created_at=$d['created_at'];$this->updated_at=$d['updated_at']??$d['created_at']; }
    public static function findById(int $id): ?self { $db=Database::getInstance();$stmt=$db->prepare('SELECT * FROM sports_events WHERE id=? LIMIT 1');$stmt->execute([$id]);$row=$stmt->fetch();return $row?new self($row):null; }
    public static function findAll(array $filters=[],int $page=1,int $perPage=20): array { $db=Database::getInstance();$where=[];$params=[];if(!empty($filters['sport_type'])){$where[]='sport_type=?';$params[]=$filters['sport_type'];}if(!empty($filters['status'])){$where[]='status=?';$params[]=$filters['status'];}if(!empty($filters['date_from'])){$where[]='event_date>=?';$params[]=$filters['date_from'];}if(!empty($filters['date_to'])){$where[]='event_date<=?';$params[]=$filters['date_to'];}$wc=$where?'WHERE '.implode(' AND ',$where):'';$offset=($page-1)*$perPage;$stmt=$db->prepare("SELECT * FROM sports_events {$wc} ORDER BY event_date DESC LIMIT ? OFFSET ?");$params[]=$perPage;$params[]=$offset;$stmt->execute($params);return array_map(fn($r)=>new self($r),$stmt->fetchAll()); }
    public static function create(array $d): self { $db=Database::getInstance();$stmt=$db->prepare('INSERT INTO sports_events (title,description,sport_type,event_date,location,team1_id,team2_id,status,created_by) VALUES (?,?,?,?,?,?,?,?,?)');$stmt->execute([$d['title'],$d['description']??null,$d['sport_type'],$d['event_date'],$d['location']??null,$d['team1_id']??null,$d['team2_id']??null,$d['status']??'scheduled',$d['created_by']]);return self::findById((int)$db->lastInsertId()); }
    public function updateScore(int $team1,int $team2): bool { $db=Database::getInstance();$stmt=$db->prepare('UPDATE sports_events SET team1_score=?,team2_score=? WHERE id=?');return $stmt->execute([$team1,$team2,$this->id]); }
    public function updateStatus(string $status): bool { $db=Database::getInstance();$stmt=$db->prepare('UPDATE sports_events SET status=? WHERE id=?');return $stmt->execute([$status,$this->id]); }
    public function toArray(): array { return ['id'=>$this->id,'title'=>$this->title,'description'=>$this->description,'sport_type'=>$this->sport_type,'event_date'=>$this->event_date,'location'=>$this->location,'team1_id'=>$this->team1_id,'team2_id'=>$this->team2_id,'team1_score'=>$this->team1_score,'team2_score'=>$this->team2_score,'status'=>$this->status,'created_by'=>$this->created_by,'created_at'=>$this->created_at]; }
}
