<?php
namespace App\Models;
use App\Config\Database;
class SportsTeam {
    public int $id; public string $name; public string $sport_type; public ?string $description; public ?int $captain_id; public ?int $coach_id; public string $status; public string $created_at; public string $updated_at;
    public function __construct(array $d) { $this->id=(int)$d["id"];$this->name=$d["name"];$this->sport_type=$d["sport_type"];$this->description=$d["description"]??null;$this->captain_id=isset($d["captain_id"])?(int)$d["captain_id"]:null;$this->coach_id=isset($d["coach_id"])?(int)$d["coach_id"]:null;$this->status=$d["status"];$this->created_at=$d["created_at"];$this->updated_at=$d["updated_at"]??$d["created_at"]; }
    public static function findById(int $id): ?self { $db=Database::getInstance();$stmt=$db->prepare("SELECT * FROM sports_teams WHERE id=? LIMIT 1");$stmt->execute([$id]);$row=$stmt->fetch();return $row?new self($row):null; }
    public static function findAll(array $filters=[],int $page=1,int $perPage=20): array { $db=Database::getInstance();$where=[];$params=[];if(!empty($filters["sport_type"])){$where[]="sport_type=?";$params[]=$filters["sport_type"];}if(!empty($filters["status"])){$where[]="status=?";$params[]=$filters["status"];}$wc=$where?"WHERE ".implode(" AND ",$where):"";$offset=($page-1)*$perPage;$stmt=$db->prepare("SELECT * FROM sports_teams {$wc} ORDER BY name LIMIT ? OFFSET ?");$params[]=$perPage;$params[]=$offset;$stmt->execute($params);return array_map(fn($r)=>new self($r),$stmt->fetchAll()); }
    public static function create(array $d): self { $db=Database::getInstance();$stmt=$db->prepare("INSERT INTO sports_teams (name,sport_type,description,captain_id,coach_id,status) VALUES (?,?,?,?,?,?)");$stmt->execute([$d["name"],$d["sport_type"],$d["description"]??null,$d["captain_id"]??null,$d["coach_id"]??null,$d["status"]??"active"]);return self::findById((int)$db->lastInsertId()); }
    public function update(array $d): bool { $db=Database::getInstance();$sets=[];$params=[];$allowed=["name","sport_type","description","captain_id","coach_id","status"];foreach($allowed as $f){if(array_key_exists($f,$d)){$sets[]="{$f}=?";$params[]=$d[$f];}}if(empty($sets))return false;$params[]=$this->id;$stmt=$db->prepare("UPDATE sports_teams SET ".implode(",",$sets)." WHERE id=?");return $stmt->execute($params); }
    public function toArray(): array { return ["id"=>$this->id,"name"=>$this->name,"sport_type"=>$this->sport_type,"description"=>$this->description,"captain_id"=>$this->captain_id,"coach_id"=>$this->coach_id,"status"=>$this->status,"created_at"=>$this->created_at]; }
}
